services:
  rest-server:
    container_name: nestapp
    image: node:22.11-alpine
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./src:/docker/app/src
    networks:
      - my-net

  postgres:
    build: ./database
    image: postgres:17.1-alpine3.20
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-net

volumes:
  pgdata:

networks:
  my-net:
    name: my-custom-network
    driver: bridge
